version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy
    networks:
      - backend

  service1:
    build:
      context: ./service_1
    expose:
      - "8001"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    
  service2:
    build:
      context: ./service_2
    expose:
      - "8002"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  backend:
    driver: bridge